[common]
# These are the vehicle details that appear at the top of each file
depot_name = " East London"  # Add depot name here

vehicle_details = [
    "Vehicle Name: (ie GPPA 2 | TM 3 | GD 2 | Support Navarra | Support Figo)",
    "Fleet Number:",
    "Reg Number:",
    "Vin Number:"
]

# Columns that should be omitted from the output
omissions = [
    "Vehicle/Mobile: (archived)",
    "Synced",
    "Updated",
    "User:"
]

[output]
base_path = "output"  # Base path for output files
template_path = "config/prettycard.csv.xlsx"  # Path to the Excel template

[per_job_card]
# These are the details that appear for each job card ID
sections = [
    "Ticket #1 (Eg A-Engine Road-909)",
    "Initial Diagnosis (Conducted by Mechanic)1",
    "Description of work done as per ticket",
    "Ticket #2",
    "Initial Diagnosis (Conducted by Mechanic)2",
    "Description of work done as per ticket",
    "Ticket #3",
    "Initial Diagnosis (Conducted by Mechanic)3",
    "Description of work done as per ticket",
    "Ticket #4",
    "Initial Diagnosis (Conducted by Mechanic)4",
    "Description of work done as per ticket",
    "Ticket #5",
    "Initial Diagnosis (Conducted by Mechanic)5",
    "Description of work done as per ticket",
    "Have all items in tickets been actioned?",
    "If No",
    "Job Card - East London - Images of Completed work",
    "Job Card - East London - By Signing below I confirm that Items have been actioned and completed",
    "Part Name",
    "Qty",
    "Part Cost",
    "User",
    "Submitted"
]

[formatting]
# Excel formatting settings
header_font_size = 14
subheader_font_size = 12
content_font_size = 11

# Color scheme
# Common section colors (blue theme)
common_header_color = "366092"  # Dark blue
common_subheader_color = "D9E1F2"  # Light blue

# Job card section colors (green theme)
job_card_header_color = "2F75B5"  # Dark green
job_card_subheader_color = "E2EFD9"  # Light green

# General formatting
header_color = "366092"  # Default header color
subheader_color = "D9E1F2"  # Default subheader color
separator_color = "E2EFD9"  # Default separator color

# Image and row settings
image_width = 100
image_height = 100
signature_width = 200
signature_height = 60
row_height = 75
description_row_height = 30 